# Generated by Django 5.1.3 on 2024-11-28 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('eid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=23)),
                ('city', models.CharField(max_length=23)),
                ('gender', models.CharField(choices=[('female', 'female'), ('male', 'male')], max_length=23)),
                ('age', models.IntegerField()),
                ('dob', models.DateField()),
                ('profile', models.ImageField(upload_to='profile')),
            ],
        ),
    ]
